openapi: 3.0.0
info:
  title: Job Execution API
  version: 1.0.0
  description: API for executing and monitoring asynchronous tool-based jobs

servers:
  - url: http://localhost:3000
    description: Local development server

paths:
  /api/execute:
    post:
      summary: Execute a new job
      description: Initiates a new job execution for a specified tool with given parameters
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              required:
                - tool
                - prompt
              properties:
                tool:
                  type: string
                  description: The tool to execute
                  example: google_sheets
                prompt:
                  type: string
                  description: The prompt or command to execute
                  example: "Update issue with ID 4 to status OK"
      responses:
        '200':
          description: Job successfully enqueued
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    enum: [enqueued]
                  job_id:
                    type: string
                    format: uuid
                    description: Unique identifier for the job
                example:
                  status: enqueued
                  job_id: 87fb989d-46dc-4a5c-af5d-de772f8e9ebc

  /api/result:
    get:
      summary: Get job result
      description: Retrieves the current status or result of a job
      parameters:
        - name: job_id
          in: query
          required: true
          schema:
            type: string
            format: uuid
          description: The ID of the job to check
          example: 87fb989d-46dc-4a5c-af5d-de772f8e9ebc
      responses:
        '200':
          description: Job status or result
          content:
            application/json:
              schema:
                type: object
                required:
                  - status
                  - duration
                properties:
                  status:
                    type: string
                    enum: [in_progress, complete]
                    description: Current status of the job
                  duration:
                    type: integer
                    description: Duration of the job execution in seconds
                  result:
                    type: string
                    description: JSON string containing the result data (only present when status is complete)
                    format: json
                examples:
                  in_progress:
                    value:
                      status: in_progress
                      duration: 12
                  complete:
                    value:
                      status: complete
                      duration: 45
                      result: '{"spreadsheetId":"1IABmKhzqXojrAXtR5YGvnwn7LflJuCOZUYBsBLE2uOA","updatedCells":1,"updatedColumns":1,"updatedRange":"Sheet1!F3","updatedRows":1}'

components:
  schemas:
    GoogleSheetsResult:
      type: object
      properties:
        spreadsheetId:
          type: string
          description: ID of the Google Sheet that was updated
        updatedCells:
          type: integer
          description: Number of cells updated
        updatedColumns:
          type: integer
          description: Number of columns updated
        updatedRange:
          type: string
          description: Range that was updated in A1 notation
        updatedRows:
          type: integer
          description: Number of rows updated
